# Default values for django.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Django Deployment Values
replicaCount: 1
revisionHistoryLimit: 2
image:
  repository: ghcr.io/sanoguzhan/django-helm-test
  pullPolicy: IfNotPresent
  tag: "latest"
  containerPort: 8081

command: 'gunicorn blog.wsgi -b 0.0.0.0:8081'

# Django Deployment Settings
# Init Container to collect static files
collect_static:
  enabled: false
  name: staticfiles
  command: "python3 manage.py collectstatic --noinput"

# Job to run database migrations
db_migrations:
  enabled: true
  name: db-migration
  command: "python3 manage.py migrate --noinput"
  resources: {}
  safeToEvict: true
makemigrations:
  enabled: true
  name: makemigrations
  command: "python3 manage.py makemigrations"
updatepermissions:
  enabled: true
  name: updatepermissions
  command: "python3 manage.py update_permissions"
superuser:
  enabled: true
  name: superuser
  command: "python3 manage.py superuser"
runmanagements:
  enabled: true
  name: runmanagements
  command: "python3 manage.py run_managements"
# Django Static files and Media data folders
# Set to path from working directory
data:
  staticfiles: "app/staticfiles/"
  data_media: "app/data_media/"

probes:
  liveness:
    enabled: true
    path: /healthy
  readiness:
    enabled: true
    path: /ready

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Django Service Values
service:
  type: ClusterIP
  port: 80

# Caddy Settings (Proxy Setup)
proxy:
  repository: caddy
  pullPolicy: IfNotPresent
  tag: "2.1.1-alpine"
  containerPort: 8000

# Env ConfigMap values
envConfigs:
  STATIC_ROOT: "staticfiles"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  DATABASE_URL: "postgres://sage:amphitheater@postgres:5430/amphitheater"
  RABBITMQ_URL: "amphitheater:P@ssw0rd1@rabbitmq:5672/amphitheater"
  AWS_SECRETS_MANAGER_KEY_ID: ""
  AWS_SECRETS_MANAGER_SECRET_KEY: ""
  AWS_SECRETS_MANAGER_REGION_NAME: ""
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_PASSWORD: "admin_admin"
  DJANGO_SUPERUSER_EMAIL: "sabin@gmail.com"

# Env Secret Values (Base64 encoded data)
envSecrets: {}

# Django Ingress Values
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

celery:
  # Celery Beat Values
  beat:
    enabled: true
    componentName: celery-beat
    command: 'celery -A blog.celery beat -l DEBUG'
    replicaCount: 1
    strategy: Recreate
  # Celery Worker Settings
  worker:
    componentName: celery-worker
    command: 'celery -A blog.celery worker -l DEBUG'
    replicaCount: 1
    strategy: RollingUpdate
  # Celery Flower Settings
  flower:
    componentName: celery-flower
    command: 'celery -A blog.celery flower'
    replicaCount: 1
    strategy: RollingUpdate
    service:
      type: ClusterIP
      port:
        number: 5555
        name: flower
    ingress:
      enabled: false
      annotations: {}
      hosts:
        - host: example.com
          paths:
            - path: /
              pathType: Prefix
      tls: []

# Disable subchart by setting enabled value to false
redis:
  enabled: true
  password: redis
  master:
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
  replica:
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
  volumePermissions:
    enabled: true
    runAsUser: 1001

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # Uncomment and adjust the following lines if you need resource limits and requests
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
